version: '3.0'

services:

  api:
    container_name: "api"
    hostname: api
    build:
      dockerfile: src/app/Dockerfile
      context: .
    networks:
      api: {}

    volumes:
      - ./src/app:/app
      - ./src/app/home/piccolo_migrations:/usr/src/app/home/piccolo_migrations
    ports:
      - 8000:8000
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin:/home/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - './oauth2-proxy.cfg:/oauth2-proxy.cfg'
    restart: unless-stopped
    networks:
      keycloak: { }
      api: { }
      oauth2-proxy: { }
    depends_on:
      - api
      - keycloak
    ports:
      - 4180:4180/tcp
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:10.0.0
    hostname: keycloak
    command:
      [
          '-b',
          '0.0.0.0',
          '-Djboss.socket.binding.port-offset=1000',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/realm-config',
          '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    volumes:
      - ./keycloak:/realm-config
    environment:
      KEYCLOAK_USER: admin@example.com
      KEYCLOAK_PASSWORD: password
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me

    ports:
      - 9080:9080/tcp

networks:
  postgres:
  keycloak: {}
  api: {}
  oauth2-proxy: {}



volumes:
  postgres:
  pgadmin: